markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : 12nines
production_url : http://www1.12nines.com
description: "12nines"
disqus_shortname: 12nines
analytics: UA-29359933-1
author :
  name : Rajesh Shah
  github : rajshahuk
  twitter : rajshahuk
  email: raj@12nines.com
